<?xml version="1.0"?>
<package format="3">
  <name>smart_wheelchair_gazebo</name>
  <version>0.1.0</version>
  <description>Gazebo simulation assets for the smart wheelchair.</description>
  <maintainer email="dev@example.com">SmartWheelChair</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>gz_cmake_vendor</build_depend>
  <build_depend>gz_math_vendor</build_depend>
  <build_depend>gz_msgs_vendor</build_depend>
  <build_depend>gz_plugin_vendor</build_depend>
  <build_depend>gz_sim_vendor</build_depend>
  <build_depend>gz_transport_vendor</build_depend>
  <depend>ament_index_python</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>nav_msgs</depend>
  <depend>ros_gz_bridge</depend>
  <depend>ros_gz_sim</depend>
  <depend>sensor_msgs</depend>
  <depend>smart_wheelchair_safety</depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_mppi_controller</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
